name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.8.1'

      - name: Override Flutter's Dart SDK
        run: |
          echo "export PATH=\"\$HOME/.dart-sdks/3.8.1/bin:\$PATH\"" >> $GITHUB_ENV
          dart --version

      - name: Verify Dart SDK version
        run: dart --version

      - name: Verify Flutter's Dart SDK version
        run: |
          dart --version | grep "3.8.1" || (echo "Dart SDK version mismatch!" && exit 1)
     
      - name: Verify Flutter version
        run: flutter --version | grep "3.27.1" || (echo "Flutter version mismatch!" && exit 1)
     
      - name: Flutter Upgrade
        run: flutter upgrade
            
      - name: Get dependencies
        run: flutter pub get

      - name: flutter update
        run: flutter pub outdated

      - name: Get dependencies
        run: flutter pub get

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          ndk: '27.0.12077973'
          cmake: '3.22.1'

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
