name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.8.1'

      - name: Override Flutter's Dart SDK
        run: |
          echo "export PATH=\"\$HOME/.dart-sdks/3.8.1/bin:\$PATH\"" >> $GITHUB_ENV
          dart --version

      - name: Verify Dart SDK version
        run: dart --version

      - name: Verify Flutter's Dart SDK version
        run: |
          dart --version | grep "3.8.1" || (echo "Dart SDK version mismatch!" && exit 1)

      - name: Get dependencies
        run: flutter pub get

      - name: flutter update
        run: flutter pub outdated --major-versions

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
